---
version: "3"

services:

  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WS_FALLBACK=false # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
      - RATE_LIMIT=true # Set to true to limit clients to 1000 requests per 5 min.
      - TZ=${TZ}
    expose:
      - 3000 # Web UI
    labels:
      #-- WatchTower --#
      - com.centurylinklabs.watchtower.enable=true
      #-- HomePage --#
      - homepage.group=Tools and Utilities
      - homepage.name=Pairdrop
      - homepage.icon=pairdrop.png
      - homepage.description=Transfer Files Cross-Platform
      - homepage.href=${URL}
      - homepage.siteMonitor=${URL}
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true