version: "3"

services:

  spotify-server:
    image: yooooomi/your_spotify_server:latest
    container_name: spotify-server
    restart: unless-stopped
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
      CLIENT_ENDPOINT: ${CLIENT_ENDPOINT}
      SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
    networks:
      - spotify-net
      - proxy-net

  mongo:
    image: mongo:6
    container_name: spotify-mongo
    restart: unless-stopped
    volumes:
      - ./your_spotify_db:/data/db
    networks:
      - spotify-net

  spotify-client:
    image: yooooomi/your_spotify_client:latest
    container_name: spotify-client
    restart: unless-stopped
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
    networks:
      - spotify-net
      - proxy-net

networks:
  spotify-net:
  proxy-net:
    external: true
