---
version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    labels:
      #-- WatchTower --#
      - com.centurylinklabs.watchtower.enable=true
      #-- HomePage --#
      - homepage.group=Administration and Supervision
      - homepage.name=Grafana
      - homepage.icon=grafana.svg
      - homepage.description=Analytics & monitoring
      - homepage.href=${URL}
      - homepage.siteMonitor=${URL}
      - homepage.widget.type=grafana
      - homepage.widget.url=${URL}
      - homepage.widget.username=${GRAFANA_USER}
      - homepage.widget.password=${GRAFANA_PASSWORD}
    networks:
      - monitor-net
      - proxy-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - ./prometheus:/etc/prometheus
    labels:
      #-- WatchTower --#
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    labels:
      #-- WatchTower --#
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - monitor-net

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      #-- WatchTower --#
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - monitor-net

networks:
  monitor-net:
    name: monitor-net
  proxy-net:
    external: true

volumes:
  grafana-data:
