[http.middlewares]
    [http.middlewares.security-headers.headers]
        sslRedirect = true
        stsSeconds = 63072000
        stsIncludeSubdomains = true
        stsPreload = true
        forceSTSHeader = true
        frameDeny = true
        contentTypeNosniff = true
        browserXSSFilter = true
    [http.middlewares.security-headers.headers.customResponseHeaders]
        X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex"
        Server = "Lindwen's Server"
    [http.middlewares.security-headers.headers.sslProxyHeaders]
        xForwardedProto = "https"