version: "3"

services:

  website:
    container_name: website
    image: httpd:alpine
    restart: unless-stopped
    volumes:
      - ./data:/usr/local/apache2/htdocs/
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true