version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    ports:
      #- "8000:8000" # HTTP
      #- "8443:8443" # HTTPS
      #- "8123:8123" # DYNMAP
      #- "19132:19132/udp" # BEDROCK
      - 25500-25528:25500-25528
      - 25530-25600:25530-25600
    #- "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - ./data/backups:/crafty/backups
      - ./data/logs:/crafty/logs
      - ./data/servers:/crafty/servers
      - ./data/config:/crafty/app/config
      - ./data/import:/crafty/import
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
