name: Generate Services README
on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate README
        run: |
          chmod +x .github/workflows/generate_readme.sh
          ./.github/workflows/generate_readme.sh > services.md

      - name: Commit changes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update Services README by GitHub Action
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
        run: |
          git add services.md
          git push
